name: CI Angular app through Github Actions
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: Setup
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: |
          npm test -- --configuration=ci